# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-07-17 02:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='food',
            name='name',
        ),
        migrations.AlterField(
            model_name='food',
            name='img',
            field=models.ImageField(upload_to='foods'),
        ),
    ]
