# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-07-17 06:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0002_auto_20210717_0742'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='name',
            field=models.CharField(default=True, max_length=50),
        ),
    ]
